version: 0.0.0.{build}
image: Visual Studio 2017
platform: x64
environment: 
  VULKAN_VERSION: 1.1.92.1
install:
- cmd: >-
    git submodule init 
    
    git submodule update
    
    wmic product where "description='CMake' " uninstall
    
    appveyor DownloadFile "https://github.com/Kitware/CMake/releases/download/v3.13.2/cmake-3.13.2.zip" -FileName cmake.zip
    
    7z x cmake.zip > nul
    
    move cmake-3.13.2 C:\projects\ocore\cmake
    
    dir C:\projecs\ocore
    
    dir C:\projecs\ocore\cmake
    
    dir C:\projecs\ocore\cmake\bin
    
    set PATH=C:\projects\ocore\cmake\bin;%PATH%
    
    cmake --version
    
    set VULKAN_SDK=C:\VulkanSDK\%VULKAN_VERSION%
    
    if not exist "%VULKAN_SDK%" curl -L https://vulkan.lunarg.com/sdk/download/%VULKAN_VERSION%/windows/VulkanSDK-%VULKAN_VERSION%-Installer.exe -o VulkanSDK.exe
    
    if not exist "%VULKAN_SDK%" .\VulkanSDK.exe /S

    bash -c "./make_windows.sh -cmake -release -exclude_ext_formats -no_console -strip_debug_info -env=x64"

    appveyor exit
    
cache: >-
    C:\VulkanSDK\%VULKAN_VERSION%
    
    C:/projects/ocore/deps
    
    C:/projects/ocore/builds
on_failure:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/k3rn31p4nic/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 failure $env:WEBHOOK_URL
on_success:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/k3rn31p4nic/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 success $env:WEBHOOK_URL
