version: 0.0.0.{build}
image: Visual Studio 2017
configuration: Release
platform: x64
init:
- cmd: ''
environment:
  WEBHOOK_URL:
    secure: muMZwldprBMRzGkLajQJgtatA5VKNxVtMaQ88cc1rkncBjS2diFQzJaRotAZSIQoAb5gbFw391raBujyxrVZe7iJxzB0vOC/Cx2eXx+Mct6zs3sMZq5tF7fUpbJhtrHi7Uz0byhaBMmH+XD++xdiAJ6+ihuDlv8MQp3E53p5ZfQ=
  VULKAN_VERSION: 1.1.82.1
install:
- cmd: >-
    set VULKAN_SDK=C:\VulkanSDK\%VULKAN_VERSION%
    
    if not exist "%VULKAN_SDK%" curl -L https://vulkan.lunarg.com/sdk/download/%VULKAN_VERSION%/windows/VulkanSDK-%VULKAN_VERSION%-Installer.exe -o VulkanSDK.exe
    
    if not exist "%VULKAN_SDK%" .\VulkanSDK.exe /S
    
    make_pc.bat
    
cache: C:\VulkanSDK\%VULKAN_VERSION%
build:
  project: builds/Visual Studio 15 2017 Win64/oic.sln
  parallel: true
  verbosity: minimal
notifications:
- provider: Webhook
  url: https://discordapp.com/api/webhooks/489782698265804805/AOF5sNneNK2VKPDqT7tvHW5nWQW9XkaN55KAv2YMMDdtrgbOsAE94-pjvQw-D3UplDe8
  method: POST
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
