version: 0.0.0.{build}
image: Visual Studio 2017
platform: x64
environment: 
  VULKAN_VERSION: 1.1.85.0
install:
- cmd: >-
    curl -L https://github.com/git-for-windows/git/releases/download/v2.19.1.windows.1/PortableGit-2.19.1-64-bit.7z.exe -o PortableGit-2.19.1-64-bit.exe

    PortableGit-2.19.1-64-bit.exe -y
    
    dir
    
    dir PortableGit-2.19.1-64-bit
    
    set GIT_ROOT=C:/projects/ocore/PortableGit
    
    set GIT_PATH=%GIT_ROOT%;%GIT_ROOT%/bin;%GIT_ROOT%/cmd;%GIT_ROOT%/us`/bin
    
    set str="%PATH%"

    call set str=%%str:C:\Program Files\Git\usr\bin=%GIT_PATH%%%

    echo %str%

    set PATH=%str%

    git submodule init 
    
    git submodule update
    
    set VULKAN_SDK=C:\VulkanSDK\%VULKAN_VERSION%
    
    if not exist "%VULKAN_SDK%" curl -L https://vulkan.lunarg.com/sdk/download/%VULKAN_VERSION%/windows/VulkanSDK-%VULKAN_VERSION%-Installer.exe -o VulkanSDK.exe
    
    if not exist "%VULKAN_SDK%" .\VulkanSDK.exe /S

    package_windows.sh -release -exclude_ext_formats
    
cache: >-
    C:\VulkanSDK\%VULKAN_VERSION%
    
    C:/projects/ocore/deps
    
    C:/projects/ocore/builds
on_failure:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/k3rn31p4nic/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 failure $env:WEBHOOK_URL
on_success:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/k3rn31p4nic/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 success $env:WEBHOOK_URL
