version: 0.0.0.{build}
image: Visual Studio 2017
platform: x64
environment: 
  VULKAN_VERSION: 1.1.85.0
install:
- cmd: >-
    git submodule init 
    
    git submodule update
    
    set VULKAN_SDK=C:\VulkanSDK\%VULKAN_VERSION%
    
    if not exist "%VULKAN_SDK%" curl -L https://vulkan.lunarg.com/sdk/download/%VULKAN_VERSION%/windows/VulkanSDK-%VULKAN_VERSION%-Installer.exe -o VulkanSDK.exe
    
    if not exist "%VULKAN_SDK%" .\VulkanSDK.exe /S

    git update-git-for-windows /SILENT /y

    package_windows.sh -release -exclude_ext_formats
    
cache: >-
    C:\VulkanSDK\%VULKAN_VERSION%
    
    C:/projects/ocore/deps
    
    C:/projects/ocore/builds
on_failure:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/k3rn31p4nic/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 failure $env:WEBHOOK_URL
on_success:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/k3rn31p4nic/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 success $env:WEBHOOK_URL
