language: android

# Setup android environment
android:
  components:
    - build-tools-25.2.5
    - android-24
    - sys-img-arm64-v8a-android-24

before_install:
  - yes | sdkmanager "platforms;android-24"

install:
  - cd $HOME/build/OsomiLunar/ocore
  - sudo apt remove cmake
  - curl https://cmake.org/files/v3.13/cmake-3.13.0-rc3-Linux-x86_64.tar.gz --output cmake.tar.gz
  - tar -xzf cmake.tar.gz
  - mv cmake-3.13.0-rc3-Linux-x86_64 cmake
  - export PATH="${PATH}:$HOME/build/OsomiLunar/ocore/cmake/bin"
  - curl https://dl.google.com/android/repository/android-ndk-r18b-linux-x86_64.zip --output android_ndk.zip
  - unzip -q android_ndk.zip -d ./
  - mv android-ndk-r18b ndk
  - export ANDROID_NDK=$HOME/build/OsomiLunar/ocore/ndk

# Build for arm64-v8a

script:
   - cd $HOME/build/OsomiLunar/ocore
   - chmod +x make_android.sh
   - ./make_android.sh
   - cd builds/Android/arm64-v8a
   - chmod +x run_android.sh
   - ./run_android.sh

# Discord hooks

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL

after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL