language: android

# Setup android environment
android:
  components:
    - build-tools-25.2.5
    - android-24
    - sys-img-arm64-v8a-android-24

before_install:
  - yes | sdkmanager "platforms;android-24"

script:
   - $HOME/make_android.sh
   - cd $HOME/builds/Android/arm64-v8a
   - ./run_android.sh