language: android

# Setup android environment
android:
  components:
    - build-tools-25.2.5
    - android-24

before_install:
  - yes | sdkmanager "platforms;android-24"

script:
   - ./make_android
   - cd builds/Android/arm64-v8a
   - ./run_android