language: android

# Setup android environment
android:
  components:
    - build-tools-25.2.5
    - android-24
    - sys-img-arm64-v8a-android-24

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-24 --abi arm64-v8a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

before_install:
  - yes | sdkmanager "platforms;android-24"

script:
   - ./make_android
   - cd builds/Android/arm64-v8a
   - ./run_android