language: android

# Setup android environment
android:
  components:
    - build-tools-25.2.5
    - android-24
    - sys-img-arm64-v8a-android-24

before_install:
  - yes | sdkmanager "platforms;android-24"

# Update CMake to latest (required 3.6.0)
# Update clang to latest
# Install Android NDK
install:
  - cd $HOME/build/OsomiLunar/ocore
  - sudo apt remove clang -y
  - sudo apt-get install clang -y
  - sudo apt remove cmake
  - curl https://github.com/Kitware/CMake/releases/download/v3.13.2/cmake-3.13.2-Linux-x86_64.tar.gz --output cmake.tar.gz
  - tar -xzf cmake.tar.gz
  - mv cmake-3.13.0-rc3-Linux-x86_64 cmake
  - sudo apt-get install ant
  - export PATH="${PATH}:$HOME/build/OsomiLunar/ocore/cmake/bin"
  - curl https://dl.google.com/android/repository/android-ndk-r18b-linux-x86_64.zip --output android_ndk.zip
  - unzip -q android_ndk.zip -d ./
  - mv android-ndk-r18b ndk
  - export ANDROID_NDK=$HOME/build/OsomiLunar/ocore/ndk

# Build for arm64-v8a

script:
   - cd $HOME/build/OsomiLunar/ocore
   - chmod +x make_android.sh
   - ./make_android.sh -cmake -exclude_ext_formats -strip_debug_info -jobs=2 -abi=arm64-v8a

# Discord hooks

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL

after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL