version: 0.0.0.{build}
image: Visual Studio 2017
configuration:
- Debug
- Release
platform: x64
init:
- cmd: ''
environment:
  WEBHOOK_URL:
    secure: muMZwldprBMRzGkLajQJgtatA5VKNxVtMaQ88cc1rkncBjS2diFQzJaRotAZSIQoAb5gbFw391raBujyxrVZe7iJxzB0vOC/Cx2eXx+Mct6zs3sMZq5tF7fUpbJhtrHi7Uz0byhaBMmH+XD++xdiAJ6+ihuDlv8MQp3E53p5ZfQ=
install:
- cmd: >-
    curl -L https://vulkan.lunarg.com/sdk/download/1.1.82.1/windows/VulkanSDK-1.1.82.1-Installer.exe -o VulkanSDK.exe

    .\VulkanSDK.exe /S

    set VULKAN_SDK="c:\VulkanSDK\1.1.82.1"

    make_pc.bat
build:
  project: builds/Visual Studio 15 2017 Win64/oic.sln
  parallel: true
  verbosity: minimal
notifications:
- provider: Webhook
  url: https://discordapp.com/api/webhooks/489782698265804805/AOF5sNneNK2VKPDqT7tvHW5nWQW9XkaN55KAv2YMMDdtrgbOsAE94-pjvQw-D3UplDe8
  method: POST
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false